version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=ecommerce-db
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=passwordwanda12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis-ecommerce
    ports:
      - "6390:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres_data:
  redis-data:
