name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5435:5432
        env:
          POSTGRES_DB: ecommerce-db
          POSTGRES_USER: ecommerce_user
          POSTGRES_PASSWORD: passwordwanda12345

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Wait for PostgreSQL to start
        run: |
          until pg_isready -h localhost -p 5435; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Build with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5435/ecommerce-db
          SPRING_DATASOURCE_USERNAME: ecommerce_user
          SPRING_DATASOURCE_PASSWORD: passwordwanda12345
        run: mvn clean install

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5435/ecommerce-db
          SPRING_DATASOURCE_USERNAME: ecommerce_user
          SPRING_DATASOURCE_PASSWORD: passwordwanda12345
        run: mvn test

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco/

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
